#version: '3'
services:
  test_listener_2:
    image: python_flask_soc
    volumes:
      - ./app.py:/app.py
    ports:
      - 5002:5002
    container_name: tg_notification
    command: "python app.py"
